#  -*- coding: utf-8 -*-
#  Copyright (c) 2026 Ivan LUCAS.
#  Previthys, application de gestion du DUERP (Document Unique d’Évaluation des Risques Professionnels).
#  Distribué sous licence GNU GPL.

# Generated by Django 4.2.30 on 2026-09-21 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(error_messages={'unique': 'Cette catégorie existe déjà.'}, max_length=100, unique=True, verbose_name='Nom')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'catégorie de risque',
                'verbose_name_plural': 'catégories de risques',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('utilisateurs', models.ManyToManyField(blank=True, help_text='Un utilisateur (hors super-utilisateur) ne voit que les données de ses structures et celles sans structure.', related_name='structures_duerp', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs autorisés')),
            ],
            options={
                'verbose_name': 'structure',
                'verbose_name_plural': 'structures',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='VersionDuerp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('commentaire', models.TextField(verbose_name='Motif de la mise à jour')),
                ('donnees', models.JSONField(default=list, verbose_name='Données archivées')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('structure', models.ForeignKey(blank=True, help_text='Laissez vide pour archiver toutes les structures.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'version du DUERP',
                'verbose_name_plural': 'versions du DUERP',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='UniteTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('effectif', models.PositiveIntegerField(default=0, verbose_name='Effectif')),
                ('structure', models.ForeignKey(blank=True, help_text="Laissez vide pour rendre l'unité visible de toutes les structures.", null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'unité de travail',
                'verbose_name_plural': 'unités de travail',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger', models.CharField(max_length=250, verbose_name='Danger')),
                ('situation', models.TextField(blank=True, verbose_name='Situation de travail')),
                ('gravite', models.IntegerField(choices=[(1, '1 - Minime'), (2, '2 - Significative'), (3, '3 - Grave'), (4, '4 - Très grave')], default=1, verbose_name='Gravité')),
                ('frequence', models.IntegerField(choices=[(1, '1 - Rare'), (2, '2 - Occasionnelle'), (3, '3 - Fréquente'), (4, '4 - Très fréquente')], default=1, verbose_name='Fréquence')),
                ('mesures_existantes', models.TextField(blank=True, verbose_name='Mesures existantes')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risques', to='core.categorierisque', verbose_name='Catégorie')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='core.unitetravail', verbose_name='Unité de travail')),
            ],
            options={
                'verbose_name': 'risque',
                'verbose_name_plural': 'risques',
            },
        ),
        migrations.CreateModel(
            name='ActionPrevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Action de prévention')),
                ('echeance', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='a_faire', max_length=20, verbose_name='Statut')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('risque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.risque', verbose_name='Risque')),
            ],
            options={
                'verbose_name': 'action de prévention',
                'verbose_name_plural': 'actions de prévention',
                'ordering': ['echeance'],
            },
        ),
    ]
