#  -*- coding: utf-8 -*-
#  Copyright (c) 2026 Ivan LUCAS.
#  Previthys, application de gestion du DUERP (Document Unique d’Évaluation des Risques Professionnels).
#  Distribué sous licence GNU GPL.

# Generated by Django 4.2.30 on 2026-09-22 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_categories_par_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=core.models.chemin_piece_jointe, verbose_name='Fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name="Nom d'origine")),
                ('taille', models.PositiveIntegerField(verbose_name='Taille (octets)')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('risque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='core.risque', verbose_name='Risque')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ['ajoute_le'],
            },
        ),
    ]
