#  -*- coding: utf-8 -*-
#  Copyright (c) 2026 Ivan LUCAS.
#  Previthys, application de gestion du DUERP (Document Unique d’Évaluation des Risques Professionnels).
#  Distribué sous licence GNU GPL.

# Generated by Django 4.2.30 on 2026-09-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cotation_frequence_gravite_maitrise'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorierisque',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
