#  -*- coding: utf-8 -*-
#  Copyright (c) 2026 Ivan LUCAS.
#  Previthys, application de gestion du DUERP (Document Unique d’Évaluation des Risques Professionnels).
#  Distribué sous licence GNU GPL.

# Generated by Django 4.2.30 on 2026-09-23 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_categorierisque_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20, verbose_name='Action')),
                ('modele', models.CharField(max_length=100, verbose_name="Type d'objet")),
                ('objet_repr', models.CharField(max_length=255, verbose_name='Objet concerné')),
                ('detail', models.TextField(blank=True, verbose_name='Détail')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.structure', verbose_name='Structure')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'entrée du journal',
                'verbose_name_plural': 'journal des modifications',
                'ordering': ['-horodatage'],
            },
        ),
    ]
