#  -*- coding: utf-8 -*-
#  Copyright (c) 2026 Ivan LUCAS.
#  Previthys, application de gestion du DUERP (Document Unique d’Évaluation des Risques Professionnels).
#  Distribué sous licence GNU GPL.

# Generated by Django 4.2.30 on 2026-09-23 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_journalaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='utilisateurs',
            field=models.ManyToManyField(blank=True, help_text='Un utilisateur (hors super-utilisateur) ne voit que les données de ses structures et celles sans structure.', related_name='structures', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs autorisés'),
        ),
    ]
