# Generated by Django 5.2.17 on 2026-09-29 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_structure_utilisateurs"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionprevention",
            name="cout",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Coût",
            ),
        ),
        migrations.AddField(
            model_name="actionprevention",
            name="duree",
            field=models.CharField(blank=True, max_length=100, verbose_name="Durée"),
        ),
    ]
